version: "3.7"

services:
  java:
    image: jdk
    build:
      context: .
      dockerfile: Dockerfile_jdk
    networks:
      - app_network
    ports:
      - "8080:8080"
    container_name: jdk
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: ${DB_HOST}
    depends_on:
      - db
  db:
    image: mysql
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql-java
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - app_network
networks:
  app_network:
    name: app_network
    driver: bridge